// <auto-generated />
using ASPNETCOREWebAPIAppHarbor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace ASPNETCOREWebAPIAppHarbor.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180117231318_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("ASPNETCOREWebAPIAppHarbor.Models.Marca", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Codigo");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("ASPNETCOREWebAPIAppHarbor.Models.Modelo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MarcaCodigo");

                    b.Property<string>("Nome");

                    b.HasKey("Codigo");

                    b.HasIndex("MarcaCodigo");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("ASPNETCOREWebAPIAppHarbor.Models.Modelo", b =>
                {
                    b.HasOne("ASPNETCOREWebAPIAppHarbor.Models.Marca", "Marca")
                        .WithMany("Modelo")
                        .HasForeignKey("MarcaCodigo");
                });
#pragma warning restore 612, 618
        }
    }
}
